### ISSUE TITLE
Error: No module named tkinter

### ISSUE THREAD

**Issue by lastimam** [bobvann/GPIOSim#4]
Traceback (most recent call last):
  File "GPIOSim.py", line 18, in <module>
    from tkinter import Tk, Canvas, Frame, BOTH, Menu, Label, PhotoImage
ImportError: No module named tkinter

**Comment by bobvann** [comment]
Python version?

**Comment by lastimam** [comment]
pi@raspberrypi:~/Desktop $ python -V
Python 3.5.2

**Comment by lastimam** [comment]
pi@raspberrypi:~/Desktop $ python GPIOSim.py
Traceback (most recent call last):
  File "GPIOSim.py", line 18, in <module>
    from tkinter import Tk, Canvas, Frame, BOTH, Menu, Label, PhotoImage
  File "/usr/local/lib/python3.5/tkinter/**init**.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named '_tkinter'

pi@raspberrypi:~/Desktop $ python --version
Python 3.5.2

**Comment by bobvann** [comment]
Try to import Tkinter instead of tkinter

Uppercase T

**Comment by bobvann** [comment]
but since you’re running GPIOSim on the RaspberryPi itself, I guess you did not correctly understand what GPIOSim is about :)

**Comment by lastimam** [comment]
I want to use GPIOSim to simulate GPIO outputs for testing purposes without using physical circuits. Is there other usage. Please tell me.
I changed tkinter to Tkinter in the GPIOSim.py file.  Still same problem, but the error little bit different 

```
Traceback (most recent call last):
File "GPIOSim.py", line 18, in 
from Tkinter import Tk, Canvas, Frame, BOTH, Menu, Label, PhotoImage
ImportError: No module named 'Tkinter'
```

**Comment by bobvann** [comment]
it is meant to be used on a computer. On the Raspberry it may create problems since RPi.GPIO already exists.

the purpose is to provide RPi.GPIO on your workstation.

In fact, if you’re using GPIOSim via ssh on a headless RPi, Tkinter does not exist as it is a library to create GUIs.

**Comment by bobvann** [comment]
Did you run it on your workstation and solved the problem?

**Comment by lastimam** [comment]
Hi bobvann
I installed python35.  The emulator is perfect. Thank you very much.
![gpioemu_test](https://cloud.githubusercontent.com/assets/1902058/19342611/85d1f44c-9143-11e6-86ae-ca49ff4fd7bf.png)

**Comment by lastimam** [comment]
Currently I don't have linux OS. I will let you know once I achieve. 
Thank you for following up

**Comment by ivanchen276** [comment]
My workstation os is centos6.5 ,i had installed python 3.5.1 ok,but when I run python import tkinter,it was prompt configured error,need help,tkx

**Comment by ivanchen276** [comment]
Is there anyone else can help me to fix this problem?God help me

**Comment by bobvann** [comment]
Please post complete error.

Also install tkinter and tk-devel on your machine

**Comment by ivanchen276** [comment]
I use rpm command to check the tkinter installed ok or not 
rpm -q tcl   tcl-8.4.13-4.el5
rpm -q tk  tk-8.4.13-5.el5_1.1
When I run module file import tkinter,it show no module named tkinter 
I found the tkinter path is   /usr/local/Python-3.5.1/Lib/tkinter  
Does this means tkinter installed ok 
Could you give me your mail address then i will post the error pics

**Comment by bobvann** [comment]
When using python3 you must include Tkinter, not tkinter.... Note the Uppercase T

**Comment by PedroAmorim** [comment]
Hello, 
I have the same problem on python 3.4, and could solved it by install some missing modules:
`sudo apt install python3-tk python3-pil`

And remove line:
`from PIL import Image,ImageTk`

I hope this could help you.
